[versions]
guava = "33.5.0-jre"
junit-jupiter = "6.0.1"
netty = "4.1.118.Final"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport" }
netty-codec = { module = "io.netty:netty-codec" }

[bundles]
netty = ["netty-transport", "netty-codec"]
