server:
  host: localhost
  port: 8001
  ssl:
    enabled: false

database:
  host: localhost
  port: 5432
  name: valoq
  username: valoq_auth_service
  password: auth_service_password
  ssl:
    mode: require

jwt:
  expirationSeconds: 300
