server:
  host: localhost
  port: !ENV ${PORT:-8081}
  ssl:
    enabled: false

database:
  host: !ENV ${DB_HOST:-localhost}
  port: !ENV ${DB_PORT:-5432}
  name: !ENV ${DB_NAME:-valoq}
  username: !ENV ${DB_USER}
  password: !ENV ${DB_PASSWORD}
  ssl:
    mode: require

jwt:
  expirationSeconds: !ENV ${JWT_EXPIRATION_SECONDS:-3600}
