plugins {
    id("java")
    id("application")
    id 'com.diffplug.spotless' version '7.2.1'
    id 'checkstyle'
}

def targetArch = project.findProperty('targetArch') ?: 'linux-x86_64'
def epollClassifier = (targetArch in ['linux-aarch_64', 'aarch64']) ? 'linux-aarch_64' : 'linux-x86_64'

dependencies {
    implementation platform(libs.netty.bom)
    implementation libs.bundles.netty
    implementation libs.bundles.slf4j

    implementation "${libs.netty.transport.native.epoll.get().module}:$epollClassifier"

    testImplementation libs.bundles.testing.suite
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${libs.versions.junit.get()}"
    testRuntimeOnly libs.junit.platform.launcher
}

application {
    mainClass.set("Main")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(26))
    }
}

repositories {
    mavenCentral()
}

tasks.test {
    useJUnitPlatform()
}

test {
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = false
        showExceptions = true
        showCauses = true
        showStackTraces = true
        exceptionFormat = 'full'
    }
    afterSuite { desc, result ->
        if (!desc.parent) {
            println "\nTest Summary: ${result.resultType}"
            println "  Passed: ${result.successfulTestCount}"
            println "  Failed: ${result.failedTestCount}"
            println "  Skipped: ${result.skippedTestCount}"
            println "  Total:   ${result.testCount}\n"
        }
    }
}

spotless {
    java {
        palantirJavaFormat()
        removeUnusedImports()
    }
}

checkstyle {
    toolVersion = '10.26.1'
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

tasks.named('checkstyleMain') {
    dependsOn 'spotlessApply'
}

tasks.named('check') {
    dependsOn 'test'
    dependsOn 'checkstyleMain'
}