server:
  host: localhost
  port: 8001
  ssl:
    enabled: true
    certChainPath: "cert.pem"
    privateKeyPath: "key.pem"
    keyPassword: ""

database:
  host: localhost
  port: 5432
  name: valoq
  username: valoq
  password: valoq
  sslMode: disable
  ssl:
    mode: verify-ca
    rootCertPath: "ca.crt"
    certPath: "client.crt"
    keyPath: "client.pk8"
    keyPassword: ""

jwt:
  expirationSeconds: 300
